source 'http://rubygems.org'

gem 'capybara', '<3.3'
gem 'chromedriver-helper'
gem 'cucumber'
gem 'rspec'
gem 'rubocop'
gem 'selenium-webdriver', '~>3.4'
gem 'site_prism', '2.15.1'
gem 'fastri'
gem 'rcodetools'